config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  devise_scope :user do
    match "sign_out", to: "devise/sessions#destroy", via: [:delete, :get], as: :user_log_out
  end

  resources :surveys, only: [:show] do
    member do
      get :take
      post :submit
    end
  end

  # The show endpoint is cached by Nginx, so need to submit updates
  # to a different URI. Otherwise identical to a typical resource.
  patch "open-letters/:id/update", to: "open_letters#update", as: :update_open_letter
  resources :open_letters, except: [:update], path: "open-letters"

  root to: "home#index"

end

app/models/open_letter.rb
class OpenLetter < ApplicationRecord

  belongs_to :user

  has_paper_trail

  before_create :set_defaults

  validates :title,
            length: { maximum: 100 },
            presence: true

  validates :body,
            length: { maximum: 100_000 },
            presence: true

  validates :user,
            presence: true

  scope :active?, -> { where(active: true) }

  private

  def set_defaults
    self.active = true
  end

end

app/controllers/open_letters_controller.rb
class OpenLettersController < ApplicationController

  include ActionView::Helpers::SanitizeHelper

  before_action :set_paper_trail_whodunnit
  before_action :find_open_letter, only: [:show]
  before_action :find_open_letter_by_user, only: [:edit, :update]

  caches_page :show

  def index
    @open_letters = OpenLetter.active?
  end

  def show
  end

  def new
    if current_user.present? && current_user.open_letter.present?
      flash[:notice] = "Currently limited to one Open Letter per user"
      redirect_to edit_open_letter_path(current_user.open_letter)
    end

    @open_letter = OpenLetter.new
  end

  def create
    @open_letter = OpenLetter.new(open_letter_params)
    @open_letter.user = current_user

    if @open_letter.save
      flash.clear
      redirect_to @open_letter
    else
      flash.now[:error] = @open_letter.errors.full_messages
      render "new"
    end
  end

  def edit
  end

  def update
    if @open_letter.update_attributes(open_letter_params)
      flash.clear
      expire_page action: "show", id: @open_letter.id
      redirect_to @open_letter
    else
      flash.now[:error] = @open_letter.errors.full_messages
      render "edit"
    end
  end

  def destroy
  end

  private

  def find_open_letter
    @open_letter ||= OpenLetter.find(params[:id])
  end

  def find_open_letter_by_user
    @open_letter ||= OpenLetter.find_by(id: params[:id], user: current_user.id)
  end

  def open_letter_params
    params.require(:open_letter).permit(
      :body,
      :title
    ).tap do |items|
      if items[:body].present?
        items[:body] = sanitize(
          items[:body],
          tags: %w(br p h1 h2 h3 h4 h5 ul ol li strong em strike blockquote a img)
        )
      end

      items
    end
  end
end

app/views/open_letters/_form.html.erb
<%=
  form_for(
    @open_letter,
    url: @open_letter.persisted? ? update_open_letter_path(@open_letter) : open_letters_path
  ) do |form|
%>

  <div class="row">
    <div class="two columns">
      <%= form.label :title, "Title" %>
    </div>
    <div class="ten columns">
      <%= form.text_field :title, class: "full-width" %>
    </div>
  </div>

  <div class="row">
    <div class="two columns">
      <%= form.label :body, "Body" %>
    </div>
    <div class="ten columns">
      <%= form.text_area :body, class: "full-width", rows: 8 %>
    </div>
  </div>

  <div class="row">
    <div class="two columns">&nbsp;</div>
    <div class="ten columns">
      <%= form.submit %>
    </div>
  </div>

<% end %>

<script>
  $("#open_letter_body").trumbowyg({
    btns: [
      ["undo", "redo"],
      ["formatting"],
      "btnGrp-semantic",
      ["link"],
      ["insertImage"],
      "btnGrp-lists",
      ["removeformat"],
      ["fullscreen"]
    ],
    removeformatPasted: true
  })
</script>

app/views/open_letters/_login.html.erb
<div class="callout">
  <h3>Getting Started</h3>

  <p>Any Swampscott community member is welcome to share their perspective with an open letter.</p>
  
  <p>To prevent fraud and abuse, a valid Facebook account is required.</p>

  <p><a class="button button-primary" href="<%= user_facebook_omniauth_authorize_path %>">Log in</a></p>
</div>

app/views/open_letters/edit.html.erb
<div class="page-lead">
  <div class="page-heading">

  </div>
  <div class="page-actions"></div>
</div>

<div class="page-main">
  <div class="page-content container">
    <%= render "layouts/alerts" %>

    <% if current_user.present? %>
      <%= render "open_letters/form" %>
    <% else %>
      <%= render "open_letters/login" %>
    <% end %>
  </div>
</div>

app/views/open_letters/index.html.erb
<div class="page-lead">
  <div class="page-heading">
  </div>
  <div class="page-actions"></div>
</div>

<div class="page-main">
  <div class="page-content container">
    <%= render "layouts/alerts" %>

    <div class="callout">
      <h3>Share Your Perspective</h3>

      <p>Are you a Swampscott community member? We'd love to hear your perspective.</p>

      <p><a class="button" href="<%= new_open_letter_path %>">Write an Open Letter</a></p>
    </div>
    <h3>All Open Letters</h3>
    <% if @open_letters.present? %>
    <ul class="open-letters">
      <% @open_letters.map do |letter| %>
      <li>
        <span class="title"><%= link_to letter.title, open_letter_path(letter) %></span>
      </li>
      <% end %>
    </ul>
    <% end %>
  </div>
</div>

app/views/open_letters/new.html.erb
<div class="page-lead">
  <div class="page-heading">

  </div>
  <div class="page-actions"></div>
</div>

<div class="page-main">
  <div class="page-content container">
    <%= render "layouts/alerts" %>

    <% if current_user.present? %>
      <%= render "open_letters/form" %>
    <% else %>
      <%= render "open_letters/login" %>
    <% end %>
  </div>
</div>

app/views/open_letters/show.html.erb
<div class="page-lead">
  <div class="page-heading">

  </div>
  <div class="page-actions"></div>
</div>


<div class="page-main">
  <div class="page-content container">
    <%= render "layouts/alerts" %>

    <h5 class="section-heading"><%= link_to "Open Letters", open_letters_path %></h5>
    <div class="open-letter-container">
      <h1 class="open-letter-title"><%= @open_letter.title %></h1>
      <div class="open-letter-body"><%= raw @open_letter.body %></div>
      <hr>
      <div class="open-letter-author">
        <p>
          <strong><%= @open_letter.user %></strong><br/>
          <em><%= @open_letter.updated_at.strftime("%B %d, %Y") %></em>
        </p>
      </div>
    </div>
  </div>
</div>