config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  devise_scope :user do
    match "sign_out", to: "devise/sessions#destroy", via: [:delete, :get], as: :user_log_out
  end

  resources :surveys, only: [:show] do
    member do
      get :take
      post :submit
    end
  end

  # The show endpoint is cached by Nginx, so need to submit updates
  # to a different URI. Otherwise identical to a typical resource.
  patch "open-letters/:id/update", to: "open_letters#update", as: :update_open_letter
  resources :open_letters, except: [:update], path: "open-letters"

  root to: "home#index"

end

app/models/survey.rb
class Survey < ApplicationRecord

  has_many :questions

  def to_s
    slug
  end

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

  before_action :find_survey
  before_action :find_questions, only: [:submit]
  before_action :find_user_answers, only: [:take]

  caches_page :show

  def show
    calculate_results
  end

  def take
  end

  def submit
    update_user
    save_answers
    redirect_to "/surveys/#{@survey.slug}/"
  end

  private

  def find_survey
    @survey ||= Survey
      .includes(:questions)
      .find_by(slug: params[:id]) || Survey.find(id: params[:id])
  end

  def find_questions
    @questions ||= Question.where(
      survey: @survey
    )
  end

  def find_user_answers
    @answers ||= Answer
      .includes(:question)
      .where(survey: @survey, user: current_user)
      .group_by { |answer| answer.question.slug }
  end

  def update_user
    current_user.update_attributes(user_params)
  end

  def save_answers
    answer_params.map do |key, value|
      question = @questions.find_by(slug: key)
      raise Exception, "Could not find question #{key}" unless question.present?
      answer = Answer.find_or_create_by(
        question: question,
        survey: @survey,
        user: current_user
      )
      answer.update_attributes(answer: value)
    end
  end

  def calculate_results
    @results_by_question = Answer
      .joins(:question)
      .where(survey: @survey)
      .group(:"questions.slug")
      .count

    @results_by_answer = Answer
      .joins(:question)
      .where(survey: @survey)
      .where("questions.response_type" => :multiple_choice)
      .group("questions.slug", :answer)
      .count
      .reduce({}) do |acc, (key, value)|
        # Query returns compound key, e.g. {[1,2,3]: 5}
        # JS doesn't support compound object keys, so convert to single value
        # string, e.g. `{"1:2:3": 5}`
        acc["#{key[0]}:#{key[1]}"] = value
        acc
      end

    # Note: Temporarily disabled until group visualizations are ready
    #
    # @results_by_group = Answer
    #   .joins(:question, :user)
    #   .where(survey: @survey)
    #   .where("questions.response_type" => :multiple_choice)
    #   .group("questions.slug", :answer, "users.group")
    #   .count
    #   .reduce({}) do |acc, (key, value)|
    #     # Query returns compound key, e.g. {[1,2,3]: 5}
    #     # JS doesn't support compound object keys, so convert to single value
    #     # string, e.g. `{"1:2:3": 5}`
    #     acc["#{key[0]}:#{key[1]}:#{key[2]}"] = value
    #     acc
    #   end
  end

  def user_params
    params.require(:user).permit(
      :group,
      :street_address
    ).reject do |_key, value|
      value.blank?
    end
  end

  def answer_params
    params.require(:answers).permit(
      :pro_tourism,
      :pro_property_values,
      :pro_personal_use,
      :pro_transportation,
      :pro_cleanup_land,
      :pro_other,
      :pro_top,
      :con_property_value,
      :con_loss_of_land,
      :con_privacy,
      :con_safety,
      :con_building_costs,
      :con_maintenance_costs,
      :con_other,
      :con_top,
      :support,
      :town_vote,
      :town_action,
      :survey_feedback
    ).reject do |_key, value|
      value.blank?
    end
  end
end

app/helpers/surveys_helper.rb
module SurveysHelper
  def element(type, name, label, current = nil)
    update_call_count
    render  partial: "surveys/elements/#{type}",
            locals: {
              name: name,
              label: label,
              current: current,
              classes: classes
            }
  end

  def get_answer(key)
    records = @answers.fetch(key, nil)
    return nil unless records.present?
    records.first.answer.to_s
  end

  private

  def update_call_count
    @call_count = 0 unless @call_count.present?
    @call_count += 1
  end

  def classes
    @call_count.even? ? "even" : "odd"
  end
end

app/views/surveys/may-2017/_login.html.erb
<div class="callout">
  <h3>Getting Started</h3>

  <p>The first step to take the May 2017 survey is to log in with Facebook.</p>

  <p><a class="button button-primary" href="<%= user_facebook_omniauth_authorize_path %>">Log in</a></p>
</div>

<p><small>Personal information will never be shared. Responses will always be presented anonymously and in groups.</small></p>

app/views/surveys/may-2017/_results.html.erb
<div class="callout">
  <h3>Take the Survey</h3>

  <p>Are you a Swampscott community member? We'd love to hear from you.</p>

  <p><a class="button" href="<%= take_survey_path "may-2017" %>">Take the Survey</a></p>
</div>

<div>
  <h1>May 2017 Survey Results</h1>

  <p>Results are regenerated every 5 minutes. Last generated on <%= Time.now.strftime "%B %-d, %Y" %> at <%= Time.now.strftime "%l:%M %P" %>.</p>

  <h3>Benefits</h3>

  <div class="question">I value the potential...</div>
  <canvas id="pros" width="400" height="130"></canvas>

  <div class="question">Of these I most value the...</div>
  <canvas id="pro_top" width="400" height="140"></canvas>

  <h3>Concerns</h3>

  <div class="question">I am concerned about potential...</div>
  <canvas id="cons" width="400" height="156"></canvas>

  <div class="question">Of these I am most concerned about...</div>
  <canvas id="con_top" width="400" height="140"></canvas>

  <h3>Support</h3>

  <div class="question">I am...</div>
  <canvas id="support" width="400" height="140"></canvas>

  <h3>Town Meeting</h3>

  <p>On May 15, 2017 the Town of Swampscott will be voting to approve $850,000 of town funds for:</p>

  <ol>
    <li>Phase II - Fund Engineering plan</li>
    <li>Phase III - Acquiring land</li>
  </ol>

  <p>For complete details see <a target="_blank" href="http://www.town.swampscott.ma.us/Public_Documents/SwampscottMA_Calendar/S058A43EE-05A4A9C3?formid=161">Article 18 of the Town Meeting Warrant</a>.</p>

  <div class="question">I believe the Town of Swampscott should...</div>
  <canvas id="town_vote" width="400" height="140"></canvas>

</div>

<script>
  var dataByQuestion = <%= raw @results_by_question.to_json %>
  var dataByAnswer = <%= raw @results_by_answer.to_json %>
  var userGroups = <%= raw User.groups.to_json %>

  var getResultsByQuestion = function(question) {
    return dataByQuestion[question]
  }

  var getResultsByAnswer = function(question, answer) {
    var key = [question, answer].join(":")

    return dataByAnswer[key]
  }

  var getResultsByGroup = function(question, answer, group) {
    var groupId = userGroups[group]
    var key = [question, answer, groupId].join(":")

    return dataByGroup[key]
  }

  var getAnswerPercent = function (question, answer) {
    var total = getResultsByQuestion(question)
    var local = getResultsByAnswer(question, answer)

    return (local/total) * 100 || 0
  }
</script>

<script>
  var chartPieDataset = function (question, answers) {
    return {
      labels: _.values(answers),
      datasets: [{
        data: _.map(answers, function (_label, answer) {
          return getAnswerPercent(question, answer)
        }),
        backgroundColor: [
          "#FF6384",
          "#36A2EB",
          "#FFCE56",
          "#885ecc",
          "#58b941",
          "#5a77e2"
        ],
        hoverBackgroundColor: [
          "#FF6384",
          "#36A2EB",
          "#FFCE56",
          "#885ecc",
          "#58b941",
          "#5a77e2"
        ]
      }]
    }
  }

  var chartRadioDataset = function (questions) {
    return [
      {
        label: "Strongly Disagree",
        data: _.map(questions, function(question) {
          return getAnswerPercent(question, "strongly_disagree")
        }),
        backgroundColor: "rgb(255, 92, 73)",
        hoverBackgroundColor: "rgb(255, 92, 73)",
        stack: "stack0"
      },
      {
        label: "Disagree",
        data: _.map(questions, function(question) {
          return getAnswerPercent(question, "disagree")
        }),
        backgroundColor: "rgb(254, 133, 0)",
        hoverBackgroundColor: "rgb(254, 133, 0)",
        stack: "stack0"
      },
      {
        label: "Neutral",
        data: _.map(questions, function(question) {
          return getAnswerPercent(question, "neutral")
        }),
        backgroundColor: "rgb(254, 213, 0)",
        hoverBackgroundColor: "rgb(254, 213, 0)",
        stack: "stack0"
      },
      {
        label: "Agree",
        data: _.map(questions, function(question) {
          return getAnswerPercent(question, "agree")
        }),
        backgroundColor: "rgb(149, 209, 60)",
        hoverBackgroundColor: "rgb(149, 209, 60)",
        stack: "stack0"
      },
      {
        label: "Strongly Agree",
        data: _.map(questions, function(question) {
          return getAnswerPercent(question, "strongly_agree")
        }),
        backgroundColor: "rgb(0, 170, 94)",
        hoverBackgroundColor: "rgb(0, 170, 94)",
        stack: "stack0"
      }
    ]
  }

  var chartPieResults = function(id, question, answers) {
    var ctx = document.getElementById(id)

    new Chart(ctx, {
      type: "pie",
      data: chartPieDataset(question, answers),
      options: {
        animation: false,
        legend: {
          position: "left"
        }
      }
    })
  }

  var chartRadioResults = function(id, questions, labels) {
    var ctx = document.getElementById(id)

    new Chart(ctx, {
      type: "horizontalBar",
      data: {
        labels: labels,
        datasets: chartRadioDataset(questions)
      },
      options: {
        animation: false,
        scales: {
          xAxes: [{
            display: true,
            stacked: true,
          }],
          yAxes: [{
            display: true,
            stacked: true
          }]
        },
        tooltips: {
          mode: "index"
        }
      }
    })
  }

</script>


<script>
  chartRadioResults(
    "pros",
    [
      "pro_tourism",
      "pro_property_values",
      "pro_personal_use",
      "pro_transportation",
      "pro_cleanup_land"
    ],
    [
      "Increase in tourism",
      "Increase in town-wide property values",
      "Recreational space",
      "Transportation path",
      "Beautification of land"
    ]
  )

  chartPieResults(
    "pro_top",
    "pro_top",
    {
      "pro_tourism": "Increase in tourism",
      "pro_property_values": "Increase in town-wide property values",
      "pro_personal_use": "Recreational space",
      "pro_transportation": "Transportation path",
      "pro_cleanup_land": "Beautification of land"
    }
  )

  chartRadioResults(
    "cons",
    [
      "con_property_value",
      "con_loss_of_land",
      "con_privacy",
      "con_safety",
      "con_building_costs",
      "con_maintenance_costs"
    ],
    [
      "Decrease in my property value",
      "Loss of land",
      "Privacy",
      "Safety and Security",
      "Initial planning and building costs",
      "Long-term maintenance costs"
    ]
  )

  chartPieResults(
    "con_top",
    "con_top",
    {
      "con_property_value": "Decrease in my property value",
      "con_loss_of_land": "Loss of land",
      "con_privacy": "Privacy",
      "con_safety": "Safety and Security",
      "con_building_costs": "Initial planning and building costs",
      "con_maintenance_costs": "Long-term maintenance costs"
    }
  )

  chartPieResults(
    "support",
    "support",
    {
      "yes": "In favor of the idea of a Rail Trail",
      "idea_only": "In favor of the idea of a Rail Trail, but not the current proposal",
      "no": "Not in favor of the idea of a Rail Trail",
      "undecided": "I do not have enough information to form an opinion",
    }
  )

  chartPieResults(
    "town_vote",
    "town_vote",
    {
      "approve": "Approve both Phase II and Phase III",
      "first_only": "Amend the article and only approve Phase II",
      "delay": "Delay voting on Article 18",
      "against": "Vote against both phases",
      "undecided": "No opinion",
    }
  )
</script>

app/views/surveys/may-2017/_take.html.erb
<%= form_tag submit_survey_path(@survey.slug) do %>

  <h3>About You</h3>

  <div class="question">I am a...</div>
  <div class="answers">
    <%= radio_button_tag "user[group]", "abutter", current_user.group == "abutter" %>
    <%= label_tag "user_group_abutter", "Swampscott resident and rail trail property abutter" %>
    <br/>
    <%= radio_button_tag "user[group]", "resident", current_user.group == "resident" %>
    <%= label_tag "user_group_resident", "Swampscott resident" %>
    <br/>
    <%= radio_button_tag "user[group]", "other", current_user.group == "other" %>
    <%= label_tag "user_group_other", "Other" %>
  </div>

  <h3>Benefits</h3>

  <div class="question">I value the potential...</div>
  <%= element "radio", "answers[pro_tourism]", "Increase in tourism", get_answer("pro_tourism") %>
  <%= element "radio", "answers[pro_property_values]", "Increase in town-wide property values", get_answer("pro_property_values") %>
  <%= element "radio", "answers[pro_personal_use]", "Recreational space", get_answer("pro_personal_use") %>
  <%= element "radio", "answers[pro_transportation]", "Transportation path", get_answer("pro_transportation") %>
  <%= element "radio", "answers[pro_cleanup_land]", "Beautification of land", get_answer("pro_cleanup_land") %>

  <div class="row">
    <div class="question five columns">Of these I most value the...</div>
    <div class="answers seven columns">
      <%= select_tag "answers[pro_top]", options_for_select([
        ["", ""],
        ["Increase in tourism", "pro_tourism"],
        ["Increase in property values", "pro_property_values"],
        ["Recreational space", "pro_personal_use"],
        ["Transportation path", "pro_transportation"],
        ["Beautification of land", "pro_cleanup_land"]
      ], get_answer("pro_top")) %>
    </div>
  </div>

  <h3>Concerns</h3>

  <div class="question">I am concerned about potential... </div>
  <%= element "radio", "answers[con_property_value]", "Decrease in my property value", get_answer("con_property_value") %>
  <%= element "radio", "answers[con_loss_of_land]", "Loss of land", get_answer("con_loss_of_land") %>
  <%= element "radio", "answers[con_privacy]", "Privacy", get_answer("con_privacy") %>
  <%= element "radio", "answers[con_safety]", "Safety and Security", get_answer("con_safety") %>
  <%= element "radio", "answers[con_building_costs]", "Initial planning and building costs", get_answer("con_building_costs") %>
  <%= element "radio", "answers[con_maintenance_costs]", "Long-term maintenance costs", get_answer("con_maintenance_costs") %>

  <div class="row">
    <div class="question five columns">Of these I am most concerned about...</div>
    <div class="answers seven columns">
      <%= select_tag "answers[con_top]", options_for_select([
        ["", ""],
        ["Decrease in property values", "con_property_value"],
        ["Loss of land", "con_loss_of_land"],
        ["Privacy", "con_privacy"],
        ["Safety and Security", "con_safety"],
        ["Initial planning and building costs", "con_building_costs"],
        ["Long-term maintenance costs", "con_maintenance_costs"],
      ], get_answer("con_top")) %>
    </div>
  </div>

  <h3>Support</h3>

  <div class="question">I am... </div>
  <div class="answers">
    <%= radio_button_tag "answers[support]", "yes", get_answer("support") == "yes" %>
    <%= label_tag "answers_support_yes", "In favor of the idea of a Rail Trail" %>
    <br/>
    <%= radio_button_tag "answers[support]", "idea_only", get_answer("support") == "idea_only" %>
    <%= label_tag "answers_support_idea_only", "In favor of the idea of a Rail Trail, but not the current proposal" %>
    <br/>
    <%= radio_button_tag "answers[support]", "no", get_answer("support") == "no" %>
    <%= label_tag "answers_support_no", "Not in favor of the idea of a Rail Trail" %>
    <br/>
    <%= radio_button_tag "answers[support]", "undecided", get_answer("support") == "undecided" %>
    <%= label_tag "answers_support_undecided", "I do not have enough information to form an opinion" %>
  </div>

  <h3>Town Meeting</h3>

  <p>On May 15, 2017 the Town of Swampscott will be voting to approve $850,000 of town funds for:</p>

  <ol>
    <li>Phase II - Fund Engineering plan</li>
    <li>Phase III - Acquiring land</li>
  </ol>

  <p>For complete details see <a target="_blank" href="http://www.town.swampscott.ma.us/Public_Documents/SwampscottMA_Calendar/S058A43EE-05A4A9C3?formid=161">Article 18 of the Town Meeting Warrant</a>.</p>

  <div class="question">I believe the Town of Swampscott should...</div>

  <div class="answers">
    <%= radio_button_tag "answers[town_vote]", "approve", get_answer("town_vote") == "approve" %>
    <%= label_tag "answers_town_vote_approve", "Approve both Phase II and Phase III" %>
    <br/>
    <%= radio_button_tag "answers[town_vote]", "first_only", get_answer("town_vote") == "first_only" %>
    <%= label_tag "answers_town_vote_first_only", "Amend the article and only approve Phase II" %>
    <br/>
    <%= radio_button_tag "answers[town_vote]", "delay", get_answer("town_vote") == "delay" %>
    <%= label_tag "answers_town_vote_delay", "Delay voting on either phase" %>
    <br/>
    <%= radio_button_tag "answers[town_vote]", "against", get_answer("town_vote") == "against" %>
    <%= label_tag "answers_town_vote_against", "Vote against both phases" %>
    <br/>
    <%= radio_button_tag "answers[town_vote]", "undecided", get_answer("town_vote") == "undecided" %>
    <%= label_tag "answers_town_vote_undecided", "No opinion" %>
  </div>

  <h3>Next Steps</h3>

  <div class="question">What actions can the town take to address concerns and increase support for the project?</div>

  <%= text_area_tag "answers[town_action]", get_answer("town_action"), { class: "u-full-width", rows: 5 } %>

  <h3>Survey Feedback</h3>

  <div class="question">How can we improve the survey in the future? What would you like to see asked next?</div>

  <%= text_area_tag "answers[survey_feedback]", get_answer("survey_feedback"), { class: "u-full-width", rows: 4 } %>

  <%= submit_tag "Save", class: "button-primary" %>

<% end %>